version: 0.2

env:
  shell: bash
  variables:
    NODE_OPTIONS: '--max_old_space_size=4096'

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      # Install build essentials
      - yum install -y gcc-c++ make curl
      - curl -sL https://rpm.nodesource.com/setup_20.x | bash -
      - yum install -y nodejs
      - npm install -g yarn
      
  pre_build:
    commands:
      - yarn install --frozen-lockfile --network-timeout 1000000
      
  build:
    commands:
      - printf "REACT_APP_API_ENDPOINT=%s" "$API_ENDPOINT" > .env.production
      - cat .env.production
      - yarn build
      
  post_build:
    commands:
      - echo "Build completed on $(date)"

artifacts:
  base-directory: build
  files:
    - '**/*'

cache:
  paths:
    - node_modules/**/*
    - /root/.npm/**/*
    - /usr/local/lib/node_modules/**/*