version: 0.2

phases:
  build:
    commands:
      - sam deploy --resolve-s3 --no-confirm-changeset --no-fail-on-empty-changeset --stack-name valleyboy-auth --capabilities CAPABILITY_IAM --region us-east-1

artifacts:
  files:
    - template.yaml
    - '**/*'
  base-directory: .