version: 0.2
env:
  variables:
    ENVIRONMENT: dev
phases:
  install:
    runtime-versions:
      python: 3.12
    commands:
      - curl -LsSf https://astral.sh/uv/install.sh | UV_FORCE_INSTALL=1 bash
      - source $HOME/.local/bin/env
  pre_build:
    commands:
      - uv pip install -r requirements.txt
      - aws cloudformation validate-template --template-body file://template.yaml
  build:
    commands:
      - echo "No build needed for CloudFormation template"
  post_build:
    commands:
      - echo "Build completed successfully"
artifacts:
  files:
    - template.yaml
  name: BuildOutput