version: 0.2

phases:
  pre_build:
    commands:
      - aws s3api head-bucket --bucket valleyboy-lambda-code-us-east-1 2>/dev/null || aws s3api create-bucket --bucket valleyboy-lambda-code-us-east-1
      - aws s3api put-bucket-versioning --bucket valleyboy-lambda-code-us-east-1 --versioning-configuration Status=Enabled
      - aws cloudformation validate-template --template-body file://template.yaml
      
  build:
    commands:
      - cd lambda/chat
      - zip -r ../../chat-function.zip ./*
      - cd ../..
      - aws s3 cp chat-function.zip s3://valleyboy-lambda-code-us-east-1/
      
artifacts:
  files:
    - template.yaml
  name: BuildOutput