version: 0.2

env:
  variables:
    LAMBDA_CODE_BUCKET: "valleyboy-lambda-code-dev"
    LAMBDA_CODE_KEY: "chat-function.zip"

phases:
  install:
    runtime-versions:
      python: 3.12
    commands:
      - curl -LsSf https://astral.sh/uv/install.sh | sh
      - uv --version
      
  pre_build:
    commands:
      - echo "Installing dependencies with uv..."
      - cd lambda/chat
      - uv pip install -r requirements.txt --system
      - cd ../..
      
  build:
    commands:
      - echo "Packaging Lambda function..."
      - cd lambda/chat
      - zip -r ../../${LAMBDA_CODE_KEY} .
      - cd ../..
      
      - echo "Creating/updating S3 bucket for Lambda code if needed..."
      - aws s3api head-bucket --bucket ${LAMBDA_CODE_BUCKET} 2>/dev/null || aws s3 mb s3://${LAMBDA_CODE_BUCKET}
      - aws s3 cp ${LAMBDA_CODE_KEY} s3://${LAMBDA_CODE_BUCKET}/${LAMBDA_CODE_KEY}
      
      - echo "Deploying CloudFormation stack..."
      - aws cloudformation deploy \
          --template-file template.yaml \
          --stack-name valleyboy-auth-dev \
          --parameter-overrides \
            LambdaCodeBucket=${LAMBDA_CODE_BUCKET} \
            LambdaCodeKey=${LAMBDA_CODE_KEY} \
          --capabilities CAPABILITY_IAM CAPABILITY_NAMED_IAM
      
  post_build:
    commands:
      - echo "Build completed"

artifacts:
  files:
    - template.yaml
    - ${LAMBDA_CODE_KEY}
  discard-paths: yes