version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
      python: 3.12
    commands:
      - npm install -g yarn
      - cd frontend
      - yarn install --frozen-lockfile
      - cd ../lambda
      - pip install -r requirements.txt -t .
      - cd ..
      
  pre_build:
    commands:
      - aws cloudformation package --template-file template.yaml --s3-bucket $ARTIFACT_BUCKET --output-template-file packaged.yaml

  build:
    commands:
      # Build Frontend
      - cd frontend
      - echo "REACT_APP_API_ENDPOINT=$API_ENDPOINT" > .env.production
      - yarn build
      - cd ..
      
      # Build Lambda Function
      - cd lambda
      - zip -r function.zip .
      - cd ..
      
  post_build:
    commands:
      - mkdir dist
      - copy packaged.yaml dist\
      - copy lambda\function.zip dist\
      - mkdir dist\frontend
      - xcopy /E /I frontend\build\* dist\frontend\

artifacts:
  files:
    - packaged.yaml
    - lambda/function.zip
    - frontend/build/**/*
  discard-paths: no

cache:
  paths:
    - 'frontend/node_modules/**/*'
    - '/root/.npm/**/*'
    - '/root/.cache/pip/**/*'