version: 0.2

phases:
  install:
    commands:
      # Install uv
      - curl -LsSf https://astral.sh/uv/install.sh | sh
      # Add uv to PATH
      - export PATH="/root/.local/bin:$PATH"
      - uv --version 