version: 0.2

phases:
  install:
    commands:
      - curl -LsSf https://astral.sh/uv/install.sh | sh
      - export PATH="/root/.local/bin:$PATH"  # FIXED: changed from .cargo/bin
      - uv --version 