version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.12
  
  pre_build:
    commands:
      - aws cloudformation validate-template --template-body file://template.yaml
      
  build:
    commands:
      - echo "Building CloudFormation stack..."
      
  post_build:
    commands:
      - echo "Build completed"

artifacts:
  files:
    - template.yaml
    - lambda/*
  base-directory: .