version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.12
      nodejs: 20
    commands:
      # Install uv with proper installation and permissions
      - curl -LsSf https://astral.sh/uv/install.sh | sh
      - chmod +x uv
      - mv uv /usr/local/bin/
      - uv --version
  pre_build:
    commands:
      - echo Validating CloudFormation template...
      - aws cloudformation validate-template --template-body file://template.yaml
      - echo Installing dependencies...
      - uv pip install -r requirements.txt
  build:
    commands:
      - echo Packaging CloudFormation template...
      - aws cloudformation package --template-file template.yaml --s3-bucket ${ARTIFACT_BUCKET} --output-template-file packaged.yaml
  post_build:
    commands:
      - echo Build completed

artifacts:
  files:
    - packaged.yaml
    - requirements.txt
    - lambda/chat/*.py
  base-directory: '.'

cache:
  paths:
    - /root/.cache/uv/**/*
    - /root/.cache/pip/**/*