version: 0.2

phases:
  build:
    commands:
      - aws cloudformation deploy --template-file template.yaml --stack-name valleyboy-auth --capabilities CAPABILITY_IAM

artifacts:
  files:
    - template.yaml