version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
      python: 3.9
    commands:
      - pip install --upgrade pip
      - pip install aws-sam-cli
  
  pre_build:
    commands:
      - npm install
      
  build:
    commands:
      - sam build
      
  post_build:
    commands:
      - sam deploy --resolve-s3 --no-confirm-changeset --no-fail-on-empty-changeset --stack-name valleyboy-auth --capabilities CAPABILITY_IAM --region us-east-1

artifacts:
  files:
    - template.yaml
    - '**/*'
  base-directory: .