version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.12
      nodejs: 20
  pre_build:
    commands:
      - echo Installing dependencies...
      - pip install -r requirements.txt
  build:
    commands:
      - echo Packaging CloudFormation template...
      - aws cloudformation package --template-file template.yaml --s3-bucket ${ARTIFACT_BUCKET} --output-template-file packaged.yaml
  post_build:
    commands:
      - echo Build completed

artifacts:
  files:
    - packaged.yaml
    - requirements.txt
  base-directory: '.'

cache:
  paths:
    - '/root/.cache/pip/**/*'