version: 0.2
phases:
  pre_build:
    commands:
      # Clean up failed stacks
      - |
        if aws cloudformation describe-stacks --stack-name valleyboy-auth 2>&1 | grep -q "ROLLBACK_COMPLETE\|FAILED"; then
          echo "Found failed stack, deleting..."
          aws cloudformation delete-stack --stack-name valleyboy-auth
          aws cloudformation wait stack-delete-complete --stack-name valleyboy-auth
          echo "Stack deleted"
        fi
  build:
    commands:
      # Add --debug for more verbose output
      - aws cloudformation validate-template --template-body file://template.yaml
      - aws cloudformation deploy --template-file template.yaml --stack-name valleyboy-auth --capabilities CAPABILITY_IAM --no-fail-on-empty-changeset --debug

artifacts:
  files:
    - template.yaml
    - README.md
  base-directory: .