AWSTemplateFormatVersion: '2010-09-09'
Description: Cognito User Pool with Hosted UI and Chat Backend for valleyboy.io

Parameters:
  DomainPrefix:
    Type: String
    Default: valleyboy
    Description: Prefix for Cognito domain
  CustomDomain:
    Type: String
    Default: auth-dev.valleyboy.io
    Description: Custom domain for Cognito hosted UI
  LambdaCodeBucket:
    Type: String
    Default: valleyboy-lambda-code-dev
    Description: S3 bucket containing Lambda code
  LambdaCodeKey:
    Type: String
    Default: chat-function.zip
    Description: S3 key for Lambda code package
    
# Rest of the template remains the same...