AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Auth stack for valleyboy.io with quick updates

Parameters:
  Environment:
    Type: String
<<<<<<< Updated upstream
    Default: dev
    AllowedValues:
      - dev
      - prod

Conditions:
  IsProd: !Equals [!Ref Environment, 'prod']

Globals:
  Function:
    Runtime: python3.12
    Architectures:
      - arm64
    Timeout: 29
    MemorySize: 1024
=======
    Default: valleyboy
    Description: Prefix for Cognito domain
  CustomDomain:
    Type: String
    Default: auth-dev.valleyboy.io
    Description: Custom domain for Cognito hosted UI
>>>>>>> Stashed changes

Resources:
  # Certificate for custom domain
  Certificate:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: auth.valleyboy.io
      ValidationMethod: DNS
      DomainValidationOptions:
        - DomainName: auth.valleyboy.io
          HostedZoneId: Z0784189181KVEHDOY62L
    UpdateReplacePolicy: Delete
    DeletionPolicy: Delete

  # User Pool
  CognitoUserPool:
    Type: AWS::Cognito::UserPool
    Properties: 
      UserPoolName: !Sub valleyboy-${Environment}
      AdminCreateUserConfig: 
        AllowAdminCreateUserOnly: false
      AutoVerifiedAttributes:
        - email
      UsernameAttributes: 
        - email
      Schema: 
        - Name: email
          Required: true
          Mutable: false
          AttributeDataType: String
    UpdateReplacePolicy: Delete
    DeletionPolicy: Delete

  # User Pool Client
  UserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      UserPoolId: !Ref CognitoUserPool
      ClientName: !Sub valleyboy-client-${Environment}
      GenerateSecret: false
      PreventUserExistenceErrors: ENABLED
      ExplicitAuthFlows:
        - ALLOW_USER_PASSWORD_AUTH
        - ALLOW_REFRESH_TOKEN_AUTH
      AllowedOAuthFlows:
        - implicit
      AllowedOAuthScopes:
        - email
        - openid
        - profile
      CallbackURLs:
        - https://valleyboy.io/callback
      LogoutURLs:
        - https://valleyboy.io
      SupportedIdentityProviders:
        - COGNITO
      AllowedOAuthFlowsUserPoolClient: true
    UpdateReplacePolicy: Delete
    DeletionPolicy: Delete

<<<<<<< Updated upstream
  # Custom Domain
  UserPoolDomain:
    Type: AWS::Cognito::UserPoolDomain
    Properties:
      Domain: !If [IsProd, auth.valleyboy.io, !Sub auth-${Environment}.valleyboy.io]
      UserPoolId: !Ref CognitoUserPool
      CustomDomainConfig:
        CertificateArn: !Ref Certificate
    DependsOn: Certificate
    UpdateReplacePolicy: Delete
    DeletionPolicy: Delete

  # DNS Record
  DnsRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: Z0784189181KVEHDOY62L
      Name: !If [IsProd, auth.valleyboy.io, !Sub auth-${Environment}.valleyboy.io]
      Type: A
      AliasTarget:
        DNSName: !GetAtt UserPoolDomain.CloudFrontDistribution
        HostedZoneId: Z2FDTNDATAQYW2
        EvaluateTargetHealth: false
    DependsOn: UserPoolDomain
    UpdateReplacePolicy: Delete
    DeletionPolicy: Delete
=======
  CognitoCertificate:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: !Ref CustomDomain
      ValidationMethod: DNS
      DomainValidationOptions:
        - DomainName: !Ref CustomDomain
          HostedZoneId: Z0784189181KVEHDOY62L
      Tags:
        - Key: Purpose
          Value: Cognito Custom Domain

  UserPoolDomain:
    Type: AWS::Cognito::UserPoolDomain
    Properties:
      Domain: !Ref CustomDomain
      UserPoolId: !Ref UserPool
      CustomDomainConfig:
        CertificateArn: !Ref CognitoCertificate
>>>>>>> Stashed changes

Outputs:
  UserPoolId:
    Description: Cognito User Pool ID
    Value: !Ref CognitoUserPool

  UserPoolClientId:
    Description: Cognito User Pool Client ID
    Value: !Ref UserPoolClient
<<<<<<< Updated upstream

  Domain:
    Description: Custom domain for the auth UI
    Value: !If [IsProd, auth.valleyboy.io, !Sub auth-${Environment}.valleyboy.io]

  LoginUrl:
    Description: Login URL
    Value: !Sub https://${UserPoolDomain.Domain}/login?client_id=${UserPoolClient}&response_type=token&scope=email+openid+profile&redirect_uri=https://valleyboy.io/callback
=======
  CustomDomainName:
    Description: The Cognito custom domain
    Value: !Ref CustomDomain
  CertificateArn:
    Description: The ARN of the ACM certificate for the custom domain
    Value: !Ref CognitoCertificate
>>>>>>> Stashed changes
