AWSTemplateFormatVersion: '2010-09-09'
Description: Cognito User Pool with Custom Domain UI for valleyboy.io

Parameters:
  DomainName:
    Type: String
    Default: auth.valleyboy.io
    Description: Custom domain for Cognito hosted UI
  RootDomain:
    Type: String
    Default: valleyboy.io
    Description: Root domain name
  HostedZoneId:
    Type: String
    Default: Z0784189181KVEHDOY62L
    Description: Route 53 hosted zone ID for the domain

Resources:
  # SSL Certificate
  Certificate:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: !Ref DomainName
      ValidationMethod: DNS
      DomainValidationOptions:
        - DomainName: !Ref DomainName
          HostedZoneId: !Ref HostedZoneId

  # DNS Record for Custom Domain
  CustomDomainDNSRecord:
    Type: AWS::Route53::RecordSet
    DependsOn: UserPoolDomain
    Properties:
      HostedZoneId: !Ref HostedZoneId
      Name: !Ref DomainName
      Type: A
      AliasTarget:
        DNSName: !GetAtt UserPoolDomain.CloudFrontDistribution
        HostedZoneId: Z2FDTNDATAQYW2 # CloudFront's hosted zone ID is always this
        EvaluateTargetHealth: false

  # Cognito User Pool
  UserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: valleyboy-users
      AdminCreateUserConfig:
        AllowAdminCreateUserOnly: false
      AutoVerifiedAttributes:
        - email
      UsernameAttributes:
        - email
      Schema:
        - Name: email
          Required: true
          Mutable: false
          AttributeDataType: String

  # Cognito App Client
  UserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      UserPoolId: !Ref UserPool
      ClientName: valleyboy-client
      GenerateSecret: false
      AllowedOAuthFlows:
        - implicit
      AllowedOAuthScopes:
        - email
        - openid
        - profile
      CallbackURLs:
        - https://valleyboy.io/callback
      LogoutURLs:
        - https://valleyboy.io
      SupportedIdentityProviders:
        - COGNITO
      AllowedOAuthFlowsUserPoolClient: true

  # Custom Domain for Cognito
  UserPoolDomain:
    Type: AWS::Cognito::UserPoolDomain
    DependsOn: Certificate
    Properties:
      Domain: !Ref DomainName
      UserPoolId: !Ref UserPool
      CustomDomainConfig:
        CertificateArn: !Ref Certificate

Outputs:
  UserPoolId:
    Description: The ID of the Cognito User Pool
    Value: !Ref UserPool
  UserPoolClientId:
    Description: The ID of the Cognito User Pool Client
    Value: !Ref UserPoolClient
  HostedUIDomain:
    Description: The custom domain for the Cognito hosted UI
    Value: !Ref DomainName
  CertificateArn:
    Description: The ARN of the SSL certificate
    Value: !Ref Certificate
  CognitoLoginURL:
    Description: The complete login URL for the hosted UI
    Value: !Sub https://${DomainName}/login?client_id=${UserPoolClient}&response_type=token&scope=email+openid+profile&redirect_uri=https://valleyboy.io/callback